version: "3.9"
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - db-data:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec puma -C config/puma.rb"
    volumes:
      - .:/dating-app
      - bundle:/dating-app/vendor/bundle
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - db
    env_file:
      - .env.development
    networks:
      - default
      - shared-network

volumes:
  db-data:
  bundle:

networks:
  shared-network:
    external: true
